export const EQ = ["Caldera","Split A/C","Bomba de calor","Fan-coil","Climatizador","Aerotermia","VRV/VRF","Suelo radiante","Otro"];

export const RITE_CHECKLIST = {
  caldera_gas: [
    "Revisión y limpieza del quemador de gas",
    "Verificación presión de gas en quemador",
    "Limpieza del intercambiador de calor",
    "Verificación presión del circuito hidráulico",
    "Control temperatura gases de combustión",
    "Análisis de combustión (CO, CO2, O2)",
    "Revisión válvula de seguridad",
    "Comprobación vaso de expansión",
    "Verificación estanqueidad circuito gas",
    "Revisión sistema de evacuación de humos",
    "Verificación funcionamiento termostatos y sondas",
  ],
  caldera_gasoil: [
    "Revisión y limpieza del quemador de gasoil",
    "Limpieza y sustitución filtro de gasoil",
    "Purga del circuito de combustible",
    "Limpieza del intercambiador de calor",
    "Verificación presión del circuito hidráulico",
    "Control temperatura gases de combustión",
    "Análisis de combustión (CO, CO2, O2)",
    "Revisión válvula de seguridad",
    "Comprobación vaso de expansión",
    "Revisión sistema de evacuación de humos",
    "Verificación funcionamiento termostatos y sondas",
  ],
  caldera_biomasa: [
    "Limpieza del hogar y cenicero",
    "Revisión sistema de alimentación de combustible",
    "Limpieza del intercambiador de calor",
    "Verificación presión del circuito hidráulico",
    "Control temperatura gases de combustión",
    "Revisión válvula de seguridad",
    "Comprobación vaso de expansión",
    "Revisión sistema de evacuación de humos y extractor",
    "Verificación silo/depósito de combustible",
    "Verificación funcionamiento termostatos y sondas",
  ],
  split: [
    "Limpieza de filtros unidad interior",
    "Limpieza de evaporador",
    "Limpieza de condensador unidad exterior",
    "Verificación carga de gas refrigerante",
    "Comprobación temperaturas entrada/salida",
    "Revisión y limpieza bandeja de drenaje",
    "Verificación funcionamiento eléctrico y mandos",
    "Comprobación presiones de trabajo",
    "Revisión estado físico unidades interior/exterior",
  ],
  bomba_calor: [
    "Limpieza de filtros",
    "Verificación carga de gas refrigerante",
    "Comprobación presiones circuito",
    "Revisión intercambiador",
    "Verificación funcionamiento reversible calor/frío",
    "Control temperaturas entrada/salida",
    "Revisión elementos eléctricos",
    "Comprobación resistencia auxiliar",
  ],
  fancoil: [
    "Limpieza de filtros",
    "Limpieza de batería",
    "Verificación válvula de control de agua",
    "Comprobación caudal de agua",
    "Revisión bandeja de condensados",
    "Verificación funcionamiento eléctrico y velocidades",
    "Comprobación termostato ambiente",
  ],
  climatizador: [
    "Limpieza de filtros entrada/salida",
    "Revisión baterías de frío y calor",
    "Verificación humectador si existe",
    "Comprobación caudales de aire",
    "Revisión correas y rodamientos ventiladores",
    "Verificación compuertas de mezcla",
    "Control temperatura y humedad de impulsión",
    "Revisión bandeja de condensados",
  ],
  enfriadora: [
    "Limpieza condensador",
    "Verificación presiones de refrigerante",
    "Comprobación temperaturas entrada/salida agua",
    "Revisión bomba de circulación",
    "Verificación torre de refrigeración si existe",
    "Control nivel de anticongelante",
    "Revisión elementos de seguridad",
    "Comprobación aislamiento tuberías",
  ],
  vrv_vrf: [
    "Verificación unidad exterior",
    "Comprobación presiones circuito refrigerante",
    "Limpieza filtros unidades interiores",
    "Verificación control centralizado",
    "Comprobación temperaturas de trabajo",
    "Revisión conexiones eléctricas",
    "Verificación reparto de carga entre unidades",
  ],
  recuperador: [
    "Limpieza filtros entrada y salida",
    "Verificación bypass y compuertas",
    "Comprobación rendimiento del recuperador",
    "Revisión correas si tiene",
    "Verificación caudales de aire impulsión/retorno",
    "Limpieza del núcleo recuperador",
    "Control presostatos diferenciales",
  ],
};

export const TIPO_EQUIPO_OPTIONS = [
  { label:"Caldera Gas",     value:"caldera_gas" },
  { label:"Caldera Gasoil",  value:"caldera_gasoil" },
  { label:"Caldera Biomasa", value:"caldera_biomasa" },
  { label:"Split",           value:"split" },
  { label:"Bomba de calor",  value:"bomba_calor" },
  { label:"Fan-coil",        value:"fancoil" },
  { label:"Climatizador",    value:"climatizador" },
  { label:"Enfriadora",      value:"enfriadora" },
  { label:"VRV/VRF",         value:"vrv_vrf" },
  { label:"Recuperador",     value:"recuperador" },
  { label:"Otro",            value:"otro" },
];
